import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className='antialiased flex flex-col h-screen'
      >
        <Header />
        <main className="flex-1 overflow-y-auto overflow-x-hidden">

          {children}
        </main>
      </body>
    </html>
  );
}
