import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme.provider"

import "./globals.css";
const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className='antialiased flex flex-col h-screen  max-w-[1536px] mx-auto xl:border-x  overflow-hidden'
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className="flex-1 overflow-y-auto overflow-x-hidden">

            {children}
          </main>
        </ThemeProvider>

      </body>
    </html>
  );
}
